=== ayourtch/ndpmon-dot1q/config_ndpmon.dtd
<!ELEMENT config_ndpmon (ignor_autoconf, syslog_facility, admin_mail, actions_low_pri, actions_high_pri, use_reverse_hostlookups, routers, countermeasures?)>

<!ELEMENT ignor_autoconf (#PCDATA)>
<!ELEMENT syslog_facility (#PCDATA)>
<!ELEMENT admin_mail (#PCDATA)>

<!ELEMENT actions_low_pri (sendmail, syslog, exec_pipe_program)>
<!ELEMENT actions_high_pri (sendmail, syslog, exec_pipe_program)>
<!ELEMENT sendmail (#PCDATA)>
<!ELEMENT syslog (#PCDATA)>
<!ELEMENT exec_pipe_program (#PCDATA)>

<!ELEMENT use_reverse_hostlookups (#PCDATA)>
<!ELEMENT routers (router*)>
<!ELEMENT router (
    mac, lla,
    param_curhoplimit?,
    param_flags_reserved?,
    param_router_lifetime?,
    param_reachable_timer?,
    param_retrans_timer?,
    param_mtu?,
    params_volatile?,
    prefixes,
    addresses
)>

<!ELEMENT mac (#PCDATA)>
<!ELEMENT lla (#PCDATA)>
<!ELEMENT param_curhoplimit (#PCDATA)>
<!ELEMENT param_flags_reserved (#PCDATA)>
<!ELEMENT param_router_lifetime (#PCDATA)>
<!ELEMENT param_reachable_timer (#PCDATA)>
<!ELEMENT param_retrans_timer (#PCDATA)>
<!ELEMENT param_mtu (#PCDATA)>
<!ELEMENT params_volatile (#PCDATA)>

<!ELEMENT prefixes (prefix*)>
<!ELEMENT prefix (address, mask, param_flags_reserved?, param_valid_time?, param_preferred_time?)>
<!ELEMENT mask (#PCDATA)>
<!ELEMENT param_valid_time (#PCDATA)>
<!ELEMENT param_preferred_time (#PCDATA)>

<!ELEMENT addresses (address*)>
<!ELEMENT address (#PCDATA)>

<!ELEMENT countermeasures (kill_illegitimate_router?, kill_wrong_prefix?, propagate_router_params?, indicate_ndpmon_presence?)>
<!ELEMENT kill_illegitimate_router (#PCDATA)>
<!ELEMENT kill_wrong_prefix (#PCDATA)>
<!ELEMENT propagate_router_params (#PCDATA)>
<!ELEMENT indicate_ndpmon_presence (#PCDATA)>

=== ayourtch/ndpmon-dot1q/config_ndpmon.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="config.xsl" ?>
<!DOCTYPE config_ndpmon SYSTEM "/usr/local/etc/ndpmon/config_ndpmon.dtd">
<config_ndpmon>
	<ignor_autoconf>1</ignor_autoconf>
	<syslog_facility>LOG_LOCAL1</syslog_facility>
	<admin_mail>root@localhost</admin_mail>
        <actions_low_pri>
            <sendmail>1</sendmail>
            <syslog>1</syslog>
            <exec_pipe_program>/usr/local/ndpmon/create_html_table.py</exec_pipe_program>
        </actions_low_pri>
        <actions_high_pri>
            <sendmail>1</sendmail>
            <syslog>1</syslog>
            <exec_pipe_program>/usr/local/ndpmon/create_html_table.py</exec_pipe_program>
        </actions_high_pri>
        <use_reverse_hostlookups>1</use_reverse_hostlookups>
    <routers>
        <router>
                <vlan_id>105</vlan_id>
                <mac>0:1b:d5:94:e4:c6</mac>
                <lla>fe80:0:0:0:21b:d5ff:fe94:e4c6</lla>
		<prefixes>
			<prefix>
				<address>2001:db8:1234:5678:0:0:0:0</address>
				<mask>64</mask>
				<param_flags_reserved>224</param_flags_reserved>
				<param_valid_time>2592000</param_valid_time>
				<param_preferred_time>604800</param_preferred_time>
			</prefix>
		</prefixes>
		<addresses/>
        </router>

	<!-- Example of router definition
	<router>
   		<mac>00:11:22:33:44:55</mac>
		<lla>fe80:0:0:0:211:22ff:fe33:4455</lla>
		<param_curhoplimit>64</param_curhoplimit>
		<param_flags_reserved>0</param_flags_reserved>
		<param_router_lifetime>10800</param_router_lifetime>
		<param_reachable_timer>0</param_reachable_timer>
		<param_retrans_timer>0</param_retrans_timer>
		<param_mtu>0</param_mtu>
		<params_volatile>1</params_volatile>
		<prefixes>
			<prefix>
				<address>2001:db8:1234:5678:0:0:0:0</address>
				<mask>64</mask>
				<param_flags_reserved>224</param_flags_reserved>
				<param_valid_time>2592000</param_valid_time>
				<param_preferred_time>604800</param_preferred_time>
			</prefix>
		</prefixes>
		<addresses/>
	</router>
	-->
    </routers>
    <!-- Example of countermeasures configuration
        (If no configuration is present, all countermeasures will be suppressed.)
    <countermeasures>
        <kill_illegitimate_router>RESPOND</kill_illegitimate_router>
        <kill_wrong_prefix>LAUNCH AFTER 10</kill_wrong_prefix>
        <propagate_router_params>CEASE AFTER 10</propagate_router_params>
        <indicate_ndpmon_presence>SUPPRESS</indicate_ndpmon_presence>
    </countermeasures>
    -->
</config_ndpmon>
